### ISSUE TITLE
Service Broker API version check fails for 2.10

### ISSUE THREAD

**Issue by clintolson** [dwatrous/cf-service-broker-python#2]
This code in catalog() no longer works now that the service broker API is at 2.10 because float("2.10") evaluates to 2.1 which is < 2.3.

if not api_version or float(api_version) < X_BROKER_API_VERSION:
        bottle.abort(409, "Missing or incompatible %s. Expecting version %0.1f or later" % (X_BROKER_API_VERSION_NAME, X_BROKER_API_VERSION))

**Comment by dwatrous** [comment]
One way to fix this would be to set major and minor versions for the X-Broker-Api-Version value. In order to check, the header value would be split on "." and compared to the expected major and minor version numbers. Feel free to submit a pull request.

**Comment by clintolson** [comment]
Pull request submitted

**Comment by dwatrous** [comment]
Thanks for the pull request. I've merged this back in to master.
